export const skillsArray = [
  "Web Development",
  "Mobile App Development",
  "Graphic Design",
  "Content Writing",
  "Copywriting",
  "Video Editing",
  "Social Media Marketing",
  "Search Engine Optimization (SEO)",
  "Translation Services",
  "Voiceover Services",
  "Illustration",
  "Photography",
  "Data Entry",
  "Virtual Assistance",
  "Customer Support",
  "E-commerce Development",
  "UI/UX Design",
  "Software Development",
  "Accounting and Bookkeeping",
  "Project Management",
  "WordPress Development",
  "Shopify Development",
  "Magento Development",
  "PrestaShop Development",
  "WooCommerce Development",
  "BigCommerce Development",
  "Drupal Development",
  "Joomla Development",
  "Ghost Development",
  "Squarespace Development",
  "Wix Development",
  "Weebly Development",
  "React Native Development",
  "Flutter Development",
  "Ionic Development",
  "Xamarin Development",
  "Java Development",
  "C++ Development",
  "C# Development",
  "Swift Development",
  "Kotlin Development",
  "Ruby Development",
  "Go Development",
  "Python Development",
  "PHP Development",
  "Node.js Development",
  "Express.js Development",
  "MongoDB Development",
  "MySQL Development",
  "PostgreSQL Development",
  "AWS Development",
  "Azure Development",
  "Firebase Development",
  "Google Cloud Platform Development",
  "Heroku Development",
  "Digital Ocean Development",
  "React Development",
  "Angular Development",
  "Vue.js Development",
  "Gatsby Development",
  "Next.js Development",
  "Nuxt.js Development",
  "Redux Development",
  "MobX Development",
  "RxJS Development",
  "D3.js Development",
  "Three.js Development",
  "Chart.js Development",
  "Highcharts Development",
  "Styled Components Development",
  "Material UI Development",
  "Bootstrap Development",
  "Foundation Development",
  "Semantic UI Development",
  "Tailwind CSS Development",
  "Ant Design Development",
  "PrimeNG Development",
  "Ag-Grid Development",
  "Webpack Development",
  "Babel Development",
  "ESLint Development",
  "Jest Development",
  "Mocha Development",
  "Chai Development",
  "Selenium Development",
  "Cypress Development",
  "WebSockets Development",
  "OAuth Development",
  "JWT Development",
  "RESTful APIs Development",
  "GraphQL APIs Development",
  "Responsive Web Design Development",
  "Mobile-First Design Development",
  "User Experience Design Development",
  "User Interface Design Development",
  "Adobe Photoshop Development",
  "Adobe Illustrator Development",
  "Adobe XD Development",
  "Figma Development",
  "Sketch Development",
  "InVision Development",
  "Zeplin Development",
  "Bitbucket Development",
  "JIRA Development",
  "Asana Development",
  "Trello Development",
  "Slack Development",
  "Microsoft Teams Development",
  "Zoom Development",
  "Google Meet Development",
  "Skype Development",
];

export const skillsArrayArabic = [
  "تطوير الويب",
  "تطوير التطبيقات المحمولة",
  "التصميم الجرافيكي",
  "كتابة المحتوى",
  "النسخ الإعلاني",
  "تحرير الفيديو",
  "التسويق عبر وسائل التواصل الاجتماعي",
  "تحسين محركات البحث (SEO)",
  "خدمات الترجمة",
  "خدمات التعليق الصوتي",
  "الرسم والتصوير الفوتوغرافي",
  "إدخال البيانات",
  "المساعدة الافتراضية",
  "الدعم العملاء",
  "تطوير التجارة الإلكترونية",
  "تصميم واجهة المستخدم / تجربة المستخدم",
  "تطوير البرمجيات",
  "المحاسبة والمراجعة",
  "إدارة المشاريع",
  "تطوير ووردبريس",
  "تطوير Shopify",
  "تطوير Magento",
  "تطوير PrestaShop",
  "تطوير WooCommerce",
  "تطوير BigCommerce",
  "تطوير Drupal",
  "تطوير Joomla",
  "تطوير Ghost",
  "تطوير Squarespace",
  "تطوير Wix",
  "تطوير Weebly",
  "تطوير React Native",
  "تطوير Flutter",
  "تطوير Ionic",
  "تطوير Xamarin",
  "تطوير Java",
  "تطوير C++",
  "تطوير C#",
  "تطوير Swift",
  "تطوير Kotlin",
  "تطوير Ruby",
  "تطوير Go",
  "تطوير Python",
  "تطوير PHP",
  "تطوير Node.js",
  "تطوير Express.js",
  "تطوير MongoDB",
  "تطوير MySQL",
  "تطوير PostgreSQL",
  "تطوير AWS",
  "تطوير Azure",
  "تطوير Firebase",
  "تطوير Google Cloud Platform",
  "تطوير Heroku",
  "تطوير Digital Ocean",
  "تطوير React",
  "تطوير Angular",
  "تطوير Vue.js",
  "تطوير Gatsby",
  "تطوير Next.js",
  "تطوير Nuxt.js",
  "تطوير Redux",
  "تطوير MobX",
  "تطوير RxJS",
  "تطوير D3.js",
  "تطوير Three.js",
  "تطوير Chart.js",
  "تطوير Highcharts",
  "تطوير Styled Components",
  "تطوير Material UI",
  "تطوير Bootstrap",
  "تطوير Foundation",
  "تطوير Semantic UI",
  "تطوير Tailwind CSS",
  "تطوير Ant Design",
  "تطوير PrimeNG",
  "تطوير Ag-Grid",
  "تطوير Webpack",
  "تطوير Babel",
  "تطوير ESLint",
  "تطوير Jest",
  "تطوير Mocha",
  "تطوير Chai",
  "تطوير Selenium",
  "تطوير Cypress",
  "تطوير WebSockets",
  "تطوير OAuth",
  "تطوير JWT",
  "تطوير RESTful APIs",
  "تطوير GraphQL APIs",
  "تطوير Responsive Web Design",
  "تطوير Mobile-First Design",
  "تطوير User Experience Design",
  "تطوير User Interface Design",
  "تطوير Adobe Photoshop",
  "تطوير Adobe Illustrator",
  "تطوير Adobe XD",
  "تطوير Figma",
  "تطوير Sketch",
  "تطوير InVision",
  "تطوير Zeplin",
  "تطوير Bitbucket",
  "تطوير JIRA",
  "تطوير Asana",
  "تطوير Trello",
  "تطوير Slack",
  "تطوير Microsoft Teams",
  "تطوير Zoom",
  "تطوير Google Meet",
];

export const skillsArrayFrench = [
  "Développement web",
  "Développement d'applications mobiles",
  "Conception graphique",
  "Rédaction de contenu",
  "Copywriting",
  "Montage vidéo",
  "Marketing des médias sociaux",
  "Optimisation des moteurs de recherche (SEO)",
  "Services de traduction",
  "« Services de voix off »",
  "Illustration",
  "La photographie",
  "La saisie des données",
  "Assistance virtuelle",
  "Service client",
  "« Développement du commerce électronique »",
  "Conception UI/UX",
  "Développement de logiciels",
  " « Comptabilité et tenue de livres »",
  "Gestion de projet",
  "Développement WordPress",
  "Développement Shopify",
  "Développement Magento",
  "Développement PrestaShop",
  "Développement WooCommerce",
  "Développement BigCommerce",
  "Développement Drupal",
  "Développement Joomla",
  "Développement fantôme",
  "Développement de l'espace carré",
  "Développement Wix",
  "Développement Weebly",
  "Réagir au développement natif",
  "Développement flottant",
  "Développement ionique",
  "Développement Xamarin",
  "Développement Java",
  "Développement C++",
  "Développement C#",
  "Développement rapide",
  "Développement Kotlin",
  "Développement Rubis",
  "Allez au développement",
  "Développement Python",
  "Développement PHP",
  "Développement Node.js",
  "Développement Express.js",
  "Développement MongoDB",
  "Développement MySQL",
  "Développement PostgreSQL",
  "Développement AWS",
  "Développement Azur",
  "Développement Firebase",
  "Développement de la plate-forme Google Cloud",
  "Développement Heroku",
  "Développement de l'océan numérique ",
  "Réagir Développement",
  "Développement angulaire",
  "Développement Vue.js",
  "Développement Gatsby",
  "Développement Next.js",
  "Développement Nuxt.js",
  "Développement Redux",
  "Développement MobX",
  "Développement RxJS",
  "Développement D3.js",
  "Développement Three.js",
  "Développement Chart.js",
  "Développement Highcharts",
  "Développement de composants stylés",
  "Développement de l'interface utilisateur matérielle",
  "Développement Bootstrap",
  "Développement des fondations",
  "Développement d'interface utilisateur sémantique",
  "Développement CSS Tailwind",
  "Développement de conception de fourmis",
  "Développement PrimeNG",
  "Développement du réseau agricole",
  "Développement Webpack",
  "Babel Développement",
  "Développement ESLint",
  "Développement de plaisanteries",
  "Moka Développement",
  "Chai Développement",
  "Développement du sélénium",
  "Développement Cyprès",
  "Développement WebSockets",
  "Développement OAuth",
  "Développement JWT",
  "Développement d'API RESTful",
  "Développement d'API GraphQL",
  "Développement de conception de sites Web réactifs",
  "Développement de conception Mobile-First",
  "Développement de la conception de l'expérience utilisateur",
  "Développement de conception d'interface utilisateur",
  "Développement Adobe Photoshop",
  "Développement d'Adobe Illustrator",
  "Développement Adobe XD",
  "Développement Figma",
  "Développement de croquis",
  "Développement InVision",
  "Développement Zeplin",
  "Développement Bitbucket",
  "Développement JIRA",
  "Développement Asana",
  "Développement Trello",
  "« Développement mou »",
  "Développement Microsoft Teams",
  "Zoom Développement",
  "Développement Google Meet",
  "Développement Skype",
];
